### ISSUE TITLE
Pack/CNB local testing

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#149]
Don't forget to add the pack orb 

```
version: 2.1
orbs:
  buildpacks: jkutner/buildpacks@0.1.0
jobs:
  build:
    machine: true
    steps:
      - buildpacks/install-pack:
          version: "0.11.0"
```
